# Generated by Django 4.0.3 on 2022-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текс')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=30, verbose_name='Почтовый адрес')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модеринован')], max_length=200, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'db_table': 'quote',
            },
        ),
    ]
